/**
 * Docs generator — keeps the published reference in lockstep with the code.
 *
 * Sources of truth:
 *   - src/commands/registry.ts  → every `dxcrm` CLI command (name + description)
 *   - src/setup/harness-content.ts (ALL_TOOLS) → canonical MCP tool names
 *   - src/mcp/capabilities.ts (CAPABILITIES_TEXT) → tool purpose + RBAC table
 *
 * It rewrites the AUTOGEN blocks (between the markers below) in:
 *   - docs/cli-reference.md
 *   - docs/mcp-tools.md
 *   - docs/index.html
 *
 * Run: `npm run docs:generate`. The drift-guard test
 * (__tests__/docs/docs-coverage.test.ts) fails CI if a command or tool is
 * missing from the docs, so this never silently goes stale.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { ALL_COMMANDS } from "../src/commands/registry.js";
import { ALL_TOOLS } from "../src/setup/harness-content.js";
import { CAPABILITIES_TEXT } from "../src/mcp/capabilities.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DOCS = join(ROOT, "docs");

const MARK_START = "<!-- AUTOGEN:START -->";
const MARK_END = "<!-- AUTOGEN:END -->";
const GENERATED_NOTE =
  "<!-- This block is generated by scripts/generate-docs.ts — do not edit by hand. -->";

interface Tool {
  name: string;
  purpose: string;
  rbac: string;
}

interface Cmd {
  name: string;
  description: string;
}

function getTools(): Tool[] {
  const rows = [
    ...CAPABILITIES_TEXT.matchAll(/^\|\s*([a-z_]+)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|/gm),
  ]
    .map((m) => ({ name: m[1]!, purpose: m[2]!.trim(), rbac: m[3]!.trim() }))
    .filter((r) => r.name !== "Tool");
  const byName = new Map(rows.map((r) => [r.name, r]));
  const tools: Tool[] = [];
  const missing: string[] = [];
  for (const name of ALL_TOOLS as readonly string[]) {
    const row = byName.get(name);
    if (row) tools.push(row);
    else missing.push(name);
  }
  if (missing.length) {
    throw new Error(
      `capabilities.ts "Available Tools" table is missing ${missing.length} tool(s): ${missing.join(", ")}`
    );
  }
  return tools;
}

function getCommands(): Cmd[] {
  return ALL_COMMANDS.map((c) => ({
    name: c.name(),
    description: (c.description() || "").trim(),
  })).sort((a, b) => a.name.localeCompare(b.name));
}

function replaceBlock(file: string, body: string): void {
  const path = join(DOCS, file);
  const src = readFileSync(path, "utf8");
  const block = `${MARK_START}\n${GENERATED_NOTE}\n${body}\n${MARK_END}`;
  const re = new RegExp(`${MARK_START}[\\s\\S]*?${MARK_END}`);
  if (!re.test(src)) {
    throw new Error(`No AUTOGEN markers found in docs/${file}. Add:\n${MARK_START}\n${MARK_END}`);
  }
  const next = src.replace(re, block);
  if (next !== src) {
    writeFileSync(path, next);
    console.log(`✓ updated docs/${file}`);
  } else {
    console.log(`= docs/${file} already current`);
  }
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function mdCell(s: string): string {
  return s.replace(/\|/g, "\\|");
}

const tools = getTools();
const commands = getCommands();

// ── docs/cli-reference.md : complete command index ────────────────────────
{
  const lines = [
    `## Complete Command Index (${commands.length})`,
    "",
    "| Command | Description |",
    "|---|---|",
    ...commands.map((c) => `| \`dxcrm ${c.name}\` | ${mdCell(c.description)} |`),
  ];
  replaceBlock("cli-reference.md", lines.join("\n"));
}

// ── docs/mcp-tools.md : complete tool index ───────────────────────────────
{
  const lines = [
    `## Complete Tool Index (${tools.length})`,
    "",
    "| Tool | Purpose | RBAC |",
    "|---|---|---|",
    ...tools.map((t) => `| \`${t.name}\` | ${mdCell(t.purpose)} | ${mdCell(t.rbac)} |`),
  ];
  replaceBlock("mcp-tools.md", lines.join("\n"));
}

// ── docs/index.html : complete reference section ──────────────────────────
{
  const cmdRows = commands
    .map((c) => `<tr><td><code>dxcrm ${esc(c.name)}</code></td><td>${esc(c.description)}</td></tr>`)
    .join("\n");
  const toolRows = tools
    .map(
      (t) =>
        `<tr><td><code>${esc(t.name)}</code></td><td>${esc(t.purpose)}</td><td>${esc(t.rbac)}</td></tr>`
    )
    .join("\n");
  const body = [
    `<h2 id="full-cli-reference">Full CLI Reference — ${commands.length} commands</h2>`,
    `<table>`,
    `<thead><tr><th>Command</th><th>Description</th></tr></thead>`,
    `<tbody>`,
    cmdRows,
    `</tbody></table>`,
    ``,
    `<h2 id="full-mcp-reference">Full MCP Tool Reference — ${tools.length} tools</h2>`,
    `<table>`,
    `<thead><tr><th>Tool</th><th>Purpose</th><th>RBAC</th></tr></thead>`,
    `<tbody>`,
    toolRows,
    `</tbody></table>`,
  ].join("\n");
  replaceBlock("index.html", body);
}

console.log(`\nGenerated reference for ${commands.length} commands and ${tools.length} MCP tools.`);
